Add support for File Input element type
imryche/blockkit pull request #110
Opened 2024-02-28 22:39 UTC by cleavenworth

Slack added a `file_input` input element type with an API update in January 2024. This PR would add support for the `file_input` element in the builder.

2024-03-01 14:32 UTC, imryche requested changes
Hi! Thank you for the contribution. Please take a look at the few comments that I've left. I'll merge the PR immediately after they are addressed.

2024-03-01 14:32 UTC, imryche commented on blockkit/elements.py
> +    maxfiles: Optional[int] = Field(None)
I would suggest using Field(..., gt=0, le=10) instead of defining a custom validator.

2024-03-01 14:32 UTC, imryche commented on blockkit/elements.py
> +        focus_on_load: Optional[bool] = None,
According to the [Slack Docs](https://api.slack.com/reference/block-kit/block-elements#file_input) `file_input` element doesn't support `focus_on_load`.

2024-03-05 14:45 UTC, imryche commented on blockkit/elements.py
> +class FileInput(FocusableElement):
I think we should inherit from the ActionableComponent class to make the tests pass.

2024-03-05 14:48 UTC, imryche requested changes
I think we should inherit from the `ActionableComponent` class to make the tests pass

2024-03-05 14:51 UTC, cleavenworth commented
Looks like I left a reference to focus_on_load in `test_elements.py`. I've removed that and also implemented the change to use ActionableComponent.

2024-03-05 14:51 UTC, merged

2024-03-05 14:57 UTC, imryche commented
Released the changes in v1.8.0